pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:romaswe/mern-recipe-app.git
          - cd mern-recipe-app.git
          - git push --mirror git@github.com:romaswe/mern-recipe-app.git