version: '3.7'
services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        image: recepie-app-server
        container_name: recepie-app-node-server
        restart: unless-stopped
        command: npm run start
        volumes:
            - ./server/:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - '5000:5000'
        depends_on:
            - mongo
        env_file:
            - ./server/.env
        environment:
            - NODE_ENV=development
        networks:
            - app-network
    mongo:
        image: mongo
        container_name: mongodb
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - ./docker/res/db:/data/db

    mongo-express:
        image: mongo-express
        container_name: mongoexpress
        depends_on:
            - 'mongo'
        restart: always
        ports:
            - ${MONGO_EXPRESS_PORT}:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD}
            ME_CONFIG_BASICAUTH_USERNAME: ${EXPRESS_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${EXPRESS_PASSWORD}
            ME_CONFIG_MONGODB_ENABLE_ADMIN: 1
            ME_CONFIG_MONGODB_SERVER: mongo

    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        image: recepie-app-client
        container_name: recepie-app-react-client
        restart: unless-stopped
        volumes:
            - ./client/:/usr/app
            - /usr/app/node_modules
        depends_on:
            - server
        env_file:
            - ./client/.env
        ports:
            - '6688:80'
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
        driver: local
