version: '3.7'

services:
    mongo:
        image: mongo
        container_name: mongodb
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${ADMIN_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${ADMIN_PASSWORD}
        volumes:
            - ./mongodbRes/db:/data/db

    mongo-express:
        image: mongo-express
        container_name: mongoexpress
        depends_on:
            - 'mongo'
        restart: always
        ports:
            - ${PORT}:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${ADMIN_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${ADMIN_PASSWORD}
            ME_CONFIG_BASICAUTH_USERNAME: ${EXPRESS_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD: ${EXPRESS_PASSWORD}
            ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
            ME_CONFIG_MONGODB_SERVER: mongo
