// Generated by https://quicktype.io

export interface GroceriesJson {
	success: boolean;
	data: GrocerisObj;
}

export interface GrocerisObj {
	groceries: Groceri[];
	_id?: string;
	owner?: string;
	name?: string;
	size?: number;
	__v?: number;
}

export interface Groceri {
	name: string;
	amount: number;
}
