// Generated by https://quicktype.io

export interface GroupRecipesList {
    success: boolean;
    data: GroupRecipesDoc;
}

export interface GroupRecipesDoc {
    docs: GroupRecipes[];
    totalDocs: number;
    limit: number;
    totalPages: number;
    page: number;
    pagingCounter: number;
    hasPrevPage: boolean;
    hasNextPage: boolean;
    prevPage: null;
    nextPage: null;
}

export interface GroupRecipes {
    _id?: string;
    description?: string;
    groupName: string;
    notes?: string;
    recipes?: Recipe[];
    __v?: number;
}

export interface Recipe {
    _id: string;
    name: string;
    url: string;
    notes: string;
    description: string;
    categories: string[];
    ingrediens: Ingrediens[];
    instructions: string[];
    __v: number;
}

export interface Ingrediens {
    name: string;
    amount: string;
    unit: string;
    _id: string;
}
